timeout: 3

/CITADEL Kernel
    protocol: limine
    kernel_path: boot():/boot/citadel.elf
    cmdline: citadel
    module_path: boot():/modules/ramdisk.img
    module_cmdline: ramdisk

/CITADEL (Terminal)
    protocol: limine
    kernel_path: boot():/boot/citadel.elf
    cmdline: citadel citadel.mode=TERMINAL
    module_path: boot():/modules/ramdisk.img
    module_cmdline: ramdisk

/CITADEL (Recovery)
    protocol: limine
    kernel_path: boot():/boot/citadel.elf
    cmdline: citadel citadel.mode=RECOVERY citadel.recovery_code=citadel1
    module_path: boot():/modules/ramdisk.img
    module_cmdline: ramdisk


